name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update 2> /dev/null
        
    - name: Install emacs
      run: |
        sudo add-apt-repository ppa:ubuntuhandbook1/emacs
        sudo apt update
        sudo apt install emacs emacs-common

    - name: Check config
      run: |
        emacs --batch --eval="(setq package-check-signature nil)" \
        --eval="(setq buoso/configuration-pedantry-mode 'yolo)" \
        --eval="(org-babel-load-file \"config.emacs.org\")"
